### ISSUE TITLE
Ability to only display file name instead of full path

### ISSUE THREAD

**Issue by victorgdb** [EvWilson/spelunk.nvim#10]
Thanks for the plugin! It looks great!!

I'm wondering if it would be possible to have an option to only display the filename instead of the full path? For complex projects, the file name is not displayed cf screenshot.

![2024-11-07 at 11 04 00@2x](https://github.com/user-attachments/assets/f20d09e7-f3dc-463a-abd9-761398ffbeb9)

Thanks again for your work!

**Comment by EvWilson** [comment]
Hey again! Planning on getting around to this in the next couple days, but of course happy to take contributions here if you'd like.

My plan for this has two parts:
- Immediate resolution: allow the user to pass a callback to format the filenames, hopefully one that can be shared between the main UI code and the telescope extension
- Additionally: implement a new window layout system that allows the user to toggle between a horizontal/vertical layout strategy. This would be a pared-down version of what telescope does, I think: https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#layout-display. Goal would be to allow a new root-level user config of `string: 'horizontal' | 'vertical'`, and to calculate layout based on that.

If there's anything else you think you'd like to have, feel free to let me know!

**Comment by victorgdb** [comment]
If you allow me to state my dream list... It would be:

- Be able to update buffer order à-la harpoon/grapple, i.e. directly though a buffer (dd to delete a buffer, p to paste it a bit below...)
- Have a shortcut opening a prompt to select a stack by typing text (e.g. a stack named "Backend" could be retrieved by typing in a Telescope prompt like "bac")
- Be able to customize UI (highlight groups, borders...)
- Have a shortcut to select a bookmark in stack1, but also another one to directly select one in stack 2 etc. 

I'll see if I can help you in the next few weeks, but my knowledge of lua and plugin development is quite limited 🙈

But your stack feature is a killer feature, exactly what is missing from the Arrows, Harpoon & Grapple.
Keep up the good work!

**Comment by EvWilson** [comment]
Thanks so much for the ideas, these rock! I suppose to think out loud about each in turn:
- This one would be hard, as there are a fair amount of assumptions built into the code at the moment about navigating via the provided UI. I'll definitely consider it more though, as I think it's a great idea and more native to the (Neo)Vim experience.
- This should be easy! Expect it within the next week
- This shouldn't be too hard, at least the border portion, but might be deprioritized for a while as things stabilize. I'll keep it in my back pocket though.
- This is interesting to me, I may experiment with adding this, or at least providing API hooks to allow folks to do it themselves.
And no worries! Definitely still getting comfortable with it myself. Thanks again for all the feedback/notes on things - looking forward to getting more of these incorporated.

**Comment by EvWilson** [comment]
Hey @victorgdb! Just merged a PR to address the root issue of being able to show just the basename. Let me know if it solves your issue!

Will be working on some of the other things we discussed soon enough too!

**Comment by victorgdb** [comment]
Hey @EvWilson , thanks for your PR. I can't make it work tho 🤔
Here is my config file, do you see anything obvious I missed?

```
return {
  {
    -- dir = "~/Documents/Dev/nvim_plugins/spelunk.nvim",
    -- dev = true,
    'EvWilson/spelunk.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',         -- For window drawing utilities
      'nvim-telescope/telescope.nvim', -- Optional: for fuzzy search capabilities
    },
    config = function()
      require('spelunk').setup({
        base_mappings = {
          -- Toggle the UI open/closed
          toggle = '<D-e>',
          -- Add a bookmark to the current stack
          add = '<D-a>',
          -- Move to the next bookmark in the stack
          next_bookmark = '<D-h>',
          -- Move to the previous bookmark in the stack
          prev_bookmark = '<D-l>',
          -- Fuzzy-find all bookmarks
          search_bookmarks = '<leader>bf',
          -- Fuzzy-find bookmarks in current stack
          search_current_bookmarks = '<leader>bc'
        },
        window_mappings = {
          -- Move the UI cursor down
          cursor_down = 'j',
          -- Move the UI cursor up
          cursor_up = 'k',
          -- Move the current bookmark down in the stack
          bookmark_down = '<C-j>',
          -- Move the current bookmark up in the stack
          bookmark_up = '<C-k',
          -- Jump to the selected bookmark
          goto_bookmark = '<CR>',
          -- Jump to the selected bookmark in a new vertical split
          goto_bookmark_hsplit = 'x',
          -- Jump to the selected bookmark in a new horizontal split
          goto_bookmark_vsplit = 'v',
          -- Delete the selected bookmark
          delete_bookmark = 'd',
          -- Navigate to the next stack
          next_stack = 'l',
          -- Navigate to the previous stack
          previous_stack = 'h',
          -- Create a new stack
          new_stack = 'n',
          -- Delete the current stack
          delete_stack = 'D',
          -- Rename the current stack
          edit_stack = 'E',
          -- Close the UI
          close = '<Esc>',
          help = '?',
          -- Open the help menu
        },
        -- Flag to enable directory-scoped bookmark persistence
        enable_persist = true,
        -- Prefix for the Lualine integration
        -- (Change this if your terminal emulator lacks emoji support)
        statusline_prefix = '🔖',
      })
      require('spelunk').file_formatter = function(abspath)
        return vim.fn.fnamemodify(abspath, ':t')
      end
    end
  }
}
```

**Comment by mattiasbonte** [comment]
I'm also not able to achieve this functionality. I tried both of these below without success.

```
require("spelunk").setup({
     file_formatter = function(abspath)
          return vim.fn.fnamemodify(abspath, ":t")
     end,
})
```

or this

```
require("spelunk").file_formatter = function(abspath)
	return vim.fn.fnamemodify(abspath, ":t")
end
```

**Comment by EvWilson** [comment]
Ah, that would be because I lied! Accidentally typo'd in the docs. `file_formatter` -> `filename_formatter`. Doc hotfix incoming, this should work for now:
```lua
  {
    'EvWilson/spelunk.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope.nvim',
    },
    config = function()
      require('spelunk').setup({
        enable_persist = true,
      })

      require('spelunk').filename_formatter = function(abspath)
        return vim.fn.fnamemodify(abspath, ':t')
      end
    end
  },

```

**Comment by victorgdb** [comment]
It does, thanks!

**Comment by EvWilson** [comment]
Went ahead and added a horizontal layout option that can be opted into with a new toplevel config option:
```lua
  {
    'EvWilson/spelunk.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope.nvim',
    },
    config = function()
      require('spelunk').setup({
        enable_persist = true,
        orientation = 'horizontal',
      })
    end
  },
```
Added here: https://github.com/EvWilson/spelunk.nvim/pull/21

This should be another option to help deal with longer path names. I'll probably close this issue in a day or so now that we have a couple solutions for it. Thanks so much for helping out!

**Comment by mattiasbonte** [comment]
I like it! Cheers

**Comment by EvWilson** [comment]
Another addition: fuzzy searching for stacks now available as of: https://github.com/EvWilson/spelunk.nvim/pull/30
