### ISSUE TITLE
`window_mappings.bookmark_up` up not binding

### ISSUE THREAD

**Issue by mattiasbonte** [EvWilson/spelunk.nvim#18]
The `bookmark _up` bind in the `window_mappings` doesn't seem to work for me. I've retried to bind it to a few different keybindings because I thought maybe there was a conflict but without success. 

Is this a ME config issue? Or do you also experience this?

**Comment by EvWilson** [comment]
The `bookmark_up` binding seems to be working for me on the `main` branch. I might experiment with seeing if you have any conflicting bindings by running `:map <C-k>` when the menu is open.

**Comment by mattiasbonte** [comment]
Yes, there are conflicts. But strangely enough there are also conflicts on the `bookmark_down` and that seems to work ok.

I wonder though.. if this doesn't lay bare a broader issue in regards to keymaps. One would expect this plugin to keep the keymaps related to the ui window itself locally right? So that the keymaps, when the ui is open, would overrule any other existing keymaps in the config whenever the ui window is open?

Anyway,  I am far from a Neovim plugin expert :), but that's just a thought.

**Comment by EvWilson** [comment]
I'm afraid that I'd need to know a bit more about your setup and conflicting keymaps to really diagnose. The window keymaps are set with the buffer-specific `vim.api.nvim_buf_set_keymap`, which takes precedence over other keymaps set with `vim.keymap.set`. I personally have this in my config, which should create a conflict, but works fine because of the precedence:
```lua
  {
    'EvWilson/spelunk.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope.nvim',
    },
    config = function()
      require('spelunk').setup({
        base_mappings = {
          toggle = '<C-h>',
          next_bookmark = '<C-j>',
          prev_bookmark = '<C-k>',
        },
        enable_persist = true,
      })
    end
  },
```
This creates the following result when running `:map <C-j>` when the menu is open.
![CleanShot 2024-11-09 at 10 01 53@2x](https://github.com/user-attachments/assets/c7c53ee1-4fc5-4e81-938e-84a6fc109012)
What do you see when running `:map <C-k>`?

**Comment by EvWilson** [comment]
Hm, this is the config I'm working with right now to investigate:
```lua
  {
    'EvWilson/spelunk.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope.nvim',
    },
    config = function()
      require('spelunk').setup({
        window_mappings = {
          bookmark_up = '<leader>bb',
        },
        enable_persist = true,
      })
    end
  },
```
And running `:map <leader>bb` when the UI is open returns (Space is my leader):
```
n  <Space>bb   *@:lua require("spelunk").move_bookmark(-1)<CR>
                 [spelunk.nvim] Move bookmark up
```

Could you post your config block?

**Comment by mattiasbonte** [comment]
```
config = function()
		local spelunk = require("spelunk")
		spelunk.setup({
			enable_persist = true,
			orientation = "horizontal",

			base_mappings = {
				add = "<M-t>",
				toggle = "<M-e>",
				next_bookmark = "<M-j>",
				prev_bookmark = "<M-k>",
			},

			window_mappings = {
				goto_bookmark = "<CR>",
				cursor_down = "j",
				cursor_up = "k",
				bookmark_up = "<M-u",
				bookmark_down = "<M-d>",

				delete_bookmark = "dd",
				next_stack = "l",
				previous_stack = "h",
				new_stack = "n",
				delete_stack = "D",
				edit_stack = "e",
				close = "q",
				help = "?",
			},
		})

		-- Go to specific bookmark
		vim.keymap.set({ "n", "v" }, "<M-1>", function()
			spelunk.goto_bookmark_at_index(1)
		end, { desc = "Spelunk Goto Bookmark 1" })
		vim.keymap.set({ "n", "v" }, "<M-2>", function()
			spelunk.goto_bookmark_at_index(2)
		end, { desc = "Spelunk Goto Bookmark 2" })
		vim.keymap.set({ "n", "v" }, "<M-3>", function()
			spelunk.goto_bookmark_at_index(3)
		end, { desc = "Spelunk Goto Bookmark 3" })
		vim.keymap.set({ "n", "v" }, "<M-4>", function()
			spelunk.goto_bookmark_at_index(4)
		end, { desc = "Spelunk Goto Bookmark 4" })
		vim.keymap.set({ "n", "v" }, "<M-5>", function()
			spelunk.goto_bookmark_at_index(5)
		end, { desc = "Spelunk Goto Bookmark 5" })
		vim.keymap.set({ "n", "v" }, "<M-6>", function()
			spelunk.goto_bookmark_at_index(6)
		end, { desc = "Spelunk Goto Bookmark 6" })
	end
```

**Comment by EvWilson** [comment]
Your bookmark_up binding is missing a closing angled brace! :)

**Comment by mattiasbonte** [comment]
This is painful ... can't believe I missed that even while changing bindings multiple times. Sorry for wasting your time.
