### ISSUE TITLE
Base mappings execute inside window

### ISSUE THREAD

**Issue by mattiasbonte** [EvWilson/spelunk.nvim#19]
I often experience an issue when I accidentally press a wrong key-bind when the spelunk window is open, that it opens the file inside the spelunk window. And then it can sometimes get gnarly. In the sense that it sometimes overwrites the actual file with spelunk content and vice versa. 

It happens in this particular case. I bind `base_mapping.next_bookmark` to `<M-j>` and `prev` to `<M-k>`.
Then I open the spelunk window and press `<M-j>` or `<M-k>`. It will then open that file inside the spelunk window itself. Which can lead to weird behavior in the sense that when I undo it often overwrites the actual opened bookmarked file with the content of the spelunk window etc.

Weird stuff :P, hope my description is complete enough for you to figure out the root cause. But I suspect `base_mappings` should not be available inside the spelunk window itself? As only the `window_mappings` should be available when the window is open.

**Comment by EvWilson** [comment]
Does this only happen for spelunk keybinds? If so, that's an easier fix. If other keybinds are also causing issues, that would be concerning - there is a modifiable flag set to `false` from within spelunk that should prevent that. If it's the former case though, it should be easier to operate on a "call coming from inside the house".

**Comment by mattiasbonte** [comment]
So far only the spelunk base_mappings. If I would encounter any others I'll let you know!

**Comment by EvWilson** [comment]
The `next/prev_bookmark` issue should be resolved in https://github.com/EvWilson/spelunk.nvim/pull/21! If I could get your help updating and making sure that it's resolved for you, I'll go ahead and close this out after.

**Comment by mattiasbonte** [comment]
Resolved! Thank you
