### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by chuan2984** [EvWilson/spelunk.nvim#2]
hello there,
I really like the idea when i first saw your post in Reddit, i have used it for a day, i wanted to provide some feedback in case you are interested.

## The good
1. stack, very neat, hoestly dont know why this has not been explored in other file jumping plugins. 
2. the ability to view the lines you marked in the preview just like how you would traverse a a stack when debugging
3. the ability to mark lines and the file
4. multiple stacks, for someone who doesnt really do much feature work, and a lot of jumping around in different context, this is pretty great

## The bad
1. documentation of the api, i can understand as this is probably in its early stage to gather feedback
2. the UI is a little clunky, you can easily jump out of it, and not have a way to jump back in, you can accidentally close 1 with `:q`
3. not persistent, it would be crucial for me for them to be saved per branch/folder/project
4. not an easy way to cycle through the marked files in a stack without opening the UI

## The nice to have
1. integration with telescope, i'd like to have a consistent experience
2. bufferline indicator, it'd be nice to know if a file is marked or not

**Comment by GeorgiChochev** [comment]
I agree with the review, I do also find this plugin having a huge potential and I can see my self adopting to my workflow, but its a must to implement a persistent bookmarks per project.

The stacks idea is brilliant but again persistence is key

**Comment by chuan2984** [comment]
> I'd be super open to getting input on what would be helpful to have in the documentation to start! I'll try to get some of these initial asks knocked out this week when I can find the time.

thanks for the prompt replies, i really like [grapple.nvim](https://github.com/cbochs/grapple.nvim), [portal.nvim](https://github.com/cbochs/portal.nvim), and [trailblazer.nvim](https//github.com/LeonHeidelbach/trailblazer.nvim') api documentation and overall their readme is quite good.
these also happen to be your competitors 😛 , "know your enemies"

**Comment by EvWilson** [comment]
Hah, thank you! I'll go give them a peek for inspiration.

**Comment by EvWilson** [comment]
Hey guys! First changeset landed. Got a first pass at everything other than the telescope integration and bufferline indicators. Jumping out of the UI is still possible in some tricky edge cases, but should be substantially harder. Also, more effort has been made to clean up windows no matter how they were exited.
And @GeorgiChochev, persistence has landed! It's pretty rock-solid, go enable it in your config and let me know what you think!

**Comment by EvWilson** [comment]
Another update! Just included a first pass at a Telescope integration. Two new keybinds to allow you to fuzzy search over compound keys made from the stack name, file name, and line number. Let me know what you think, or if you need any tweaks/updates!

**Comment by GeorgiChochev** [comment]
Hats off sir, appreciate your work with this. 
This plugin so far is nicely integrating into my workflow, I will spend this week heavily using it and provide some additional feedback

**Comment by EvWilson** [comment]
Added a Lualine integration to satisfy the statusline nice-to-have ask, cleaned up some more small corners, and added a whole lot more in terms of documentation to the README. At this point, I think everything in this issue has been implemented! That being the case, I'll leave this issue open through the coming weekend for people (myself included) to use all the new changes for a while, and then I'll close it out. If anyone finds anything in the meantime, please let me know, and I'll address it here. Cheers!

**Comment by EvWilson** [comment]
Going to go ahead and close this out, thanks so much @chuan2984 for reaching out with the feedback! Glad to have a better project for it.

**Comment by chuan2984** [comment]
@EvWilson hey there, awesome update. The README looks amazing now, i have not updated the plugin yet since i was sick all week. will try to give it a test this next week. gooooooooood work sir
