### ISSUE TITLE
feature request: status col integration

### ISSUE THREAD

**Issue by ibrokemypie** [EvWilson/spelunk.nvim#22]
It would be great to have statuscol integration, to show marked lines and their associated number in the buffer window you are editing. 

This is what that looks like in one of the gifs provided by [arrow.nvim](https://github.com/otavioschwanck/arrow.nvim):
![](https://camo.githubusercontent.com/d9a5b6ec935120368673d6a654e0f5e28104b8e7fa0f9d01b608f71a83b31821/68747470733a2f2f692e696d6775722e636f6d2f4c6c6c395976592e676966)

**Comment by EvWilson** [comment]
I’d be happy to add this! In the middle of a larger refactor at the moment, but should free up to take a stab at it within the next week.

**Comment by EvWilson** [comment]
Should be addressed in https://github.com/EvWilson/spelunk.nvim/pull/27!

Thanks so much for the feedback, feel free to comment here again or open another issue in case anything comes up.
