### ISSUE TITLE
feature request: display all bookmarks in quickfix list

### ISSUE THREAD

**Issue by fresh2dev** [EvWilson/spelunk.nvim#23]
Similar to the `:BookmarkShowAll` capability offered by [vim-bookmarks](https://github.com/MattesGroeger/vim-bookmarks?tab=readme-ov-file#usage).

**Comment by EvWilson** [comment]
Hey! Thanks for the feedback. This should be implemented in https://github.com/EvWilson/spelunk.nvim/pull/30, with notes about the new API functions available in the README.

Thanks for opening an issue, and let me know if there's anything else you need!
