### ISSUE TITLE
feature request: remove gap between windows

### ISSUE THREAD

**Issue by martin-boeckeler** [EvWilson/spelunk.nvim#24]
hi, I really enjoy your plugin. helps a lot during the daily doing.

I just have a question.
I'm using a 27 inch display and whenever I open the spelunk window, there is a huge gap between the bookmarks pane and the preview pane (see screenshot below).

is it possible to remove this gap?

Thanks a lot and keep going!

<img width="1903" alt="image" src="https://github.com/user-attachments/assets/65da7f28-d8f8-4103-a0b9-e49647a99528">

**Comment by EvWilson** [comment]
Hey @martin-boeckeler!
Thanks so much for the kind words and feedback. I've added the ability to specify your own layout via this PR: https://github.com/EvWilson/spelunk.nvim/pull/29.
This should now allow for setting a vertical layout like you have here, a horizontal layout, or a build-your-own option! Hopefully this lets you get the experience you're looking for, let me know if there's anything else I can help with!
