### ISSUE TITLE
how to disable all keymaps?

### ISSUE THREAD

**Issue by cxwx** [EvWilson/spelunk.nvim#25]

**Comment by EvWilson** [comment]
Added the ability to skip setting keybinds in https://github.com/EvWilson/spelunk.nvim/pull/28, setting the bind value to `'NONE'` will skip binding the key entirely.

Docs updated in https://github.com/EvWilson/spelunk.nvim?tab=readme-ov-file#installationconfiguration.

Thank you for the feedback! Let me know if there's anything else I can do to help here.
