### ISSUE TITLE
Feature: Allow naming of bookmarks

### ISSUE THREAD

**Issue by baroldgene** [EvWilson/spelunk.nvim#35]
This plugin is amazing!  One thing that would be a cool addition is some ability to name the marks themselves.  This could be a text value to help remember what it is that you've bookmarked.  Ideally fuzzy finding would search either the "friendly name" or the file name.

**Comment by EvWilson** [comment]
Hey there @baroldgene! Just got done clearing up some other issues, I may be taking a stab at getting to this incrementally. I was planning already on allowing for setting a custom display function, that could for instance be used to display function/class names through Treesitter.
Sounds like this may entail adding a new additional `optional_properties` or similar to the marks. I'll have to noodle on it.

**Comment by baroldgene** [comment]
Much appreciated!  I'll be using the plugin regardless as it's very cool and actually fits a common use case I have very well.  Just thought I'd throw out the idea as a potential future feature.  

Happy to help test if you want.  I could potentially help a bit with the dev, but my time and skills are both in short supply so not sure I'd be much help.  😬

**Comment by EvWilson** [comment]
Hey @baroldgene! Sorry for the wait. This request should be addressed in https://github.com/EvWilson/spelunk.nvim/pull/46, and a guide to accomplish it is available here: https://github.com/EvWilson/spelunk.nvim/blob/main/faqs/add_and_show_mark_metadata.md

Thanks for the issue, hope this solves everything! Feel free to open it back up if there are any issues.
