### ISSUE TITLE
Feature: show symbol paths in bookmark view

### ISSUE THREAD

**Issue by oskarrrrrrr** [EvWilson/spelunk.nvim#39]
For each bookmark we could have the symbol path displayed. By symbol path of a bookmark I mean, for example, the name of the function in which the bookmark is set. In other common case it could be a class name + method name.

This would make it easier to navigate between bookmarks without having to look at the preview.

There is a plugin that displays the symbol path for the location under cursor in a statusbar/winbar: [nvim-navic](https://github.com/SmiteshP/nvim-navic). Perhaps the implementation for this plugin would be similar.

**Comment by EvWilson** [comment]
Best-effort attempt at delivering something in this vein was merged here: https://github.com/EvWilson/spelunk.nvim/pull/42

Let me know if this works for you, though I don't think I'd want to do anything more complex than this. The Treesitter API is much less ergonomic than I was expecting.

**Comment by oskarrrrrrr** [comment]
Looks good, I like it. Some thoughts/feedback below.

I could swear that `spelunk.util.get_treesitter_context` was returning `nil` even though the signature says that it returns `string` but I can't reproduce now so maybe it's ok.

Perhaps it would be better to return an empty string if the treesitter parser is not found.
<img width="663" alt="image" src="https://github.com/user-attachments/assets/b37bc957-c31a-4beb-84b5-5d006af4493f" />

It's possible to create bookmarks for any buffer, maybe there is some simple check that could prevent creating clearly useless bookmarks (e.g. you can create a bookmark to the buffer that displays the list of bookmarks).

I like that nested functions are handled:
<img width="589" alt="image" src="https://github.com/user-attachments/assets/1dea9720-958c-4b05-a621-5c62f9d4bef4" />

I found two cases in which it fails to provide a symbol but there clearly is one:
<img width="1800" alt="Screenshot 2024-12-13 at 15 55 58" src="https://github.com/user-attachments/assets/8eb5d686-6afe-4296-8197-9ee9dbbdfeb6" />

<img width="1800" alt="Screenshot 2024-12-13 at 15 55 54" src="https://github.com/user-attachments/assets/b8bd3a69-c447-439f-897c-b643d4beb2cd" />
 
---

The suggested display function (from README) could handle empty treesitter context, for example, like this:
```
function(mark)
    local ctx = spelunk_util.get_treesitter_context(mark)
    ctx = (ctx == "" and ctx) or (" - " .. ctx)
    local filename = spelunk.filename_formatter(mark.file)
    return string.format("%s:%d%s", filename, mark.line, ctx)
end
```
---

I think that it might be nice to allow displaying some info in right aligned extmarks. This is an example from neo-tree.nvim (unrelated plugin, just to show what I mean):
![image](https://github.com/user-attachments/assets/daf577e6-4d48-4ea6-960d-b25591d84088)

Personally I would love to hide the preview window since treesitter context should be good enough most of the time. Then the bookmarks list could be a simple, centered window. A bit like harpoon, except there can be multiple marks per file:
![Screenshot 2024-12-13 at 17 24 06](https://github.com/user-attachments/assets/d1338e03-069e-43f6-a3f9-d70dd2d93e18)

I would also consider using this kind of cursor in the bookmarks list:
![Screenshot 2024-12-13 at 17 28 36](https://github.com/user-attachments/assets/da7e25e6-23d3-43d3-8dbc-3d140767ad10)
Looks a bit cleaner in my opinion. I can see that you already move the cursor to a specific character but at least in my case it doesn't look that great because the cursor is quite dark (I'm using the default nvim colorscheme).
![Screenshot 2024-12-13 at 17 32 02](https://github.com/user-attachments/assets/1ba0b141-9c3e-4c6a-8df1-f353535776b0)

---

I hope it's not too much :)  I have a lot of ideas because I was thinking about implementing something similar for my plugin: [symbols.nvim](https://github.com/oskarrrrrrr/symbols.nvim)

**Comment by EvWilson** [comment]
I have a PR open (https://github.com/EvWilson/spelunk.nvim/pull/44) to address all of the above, except for the showing additional info in right-aligned extmark comment. I think that would just be more work than I'm willing to put into this at the moment, though I'd always be happy to take PRs to implement that after I get this merged.

At the time of writing, just working through why certain Lua function definitions don't seem to be getting captured, and then I'll merge this in.

**Comment by EvWilson** [comment]
It's merged! Happy to take another round of feedback here, I'll try to close this issue by the end of the weekend otherwise.

**Comment by oskarrrrrrr** [comment]
Looks good, I think that we can close it.

I ended up with this config, it centers the window.
```
orientation = {
    bookmark_dimensions = function()
        return {
            base = { width = 80, height = 30 },
            line = 0, col = 0,
        }
    end,
    help_dimensions = function()
        return {
            base = { width = 40, height = 30 },
            line = 0, col = 0,
        }
    end,
}
```
