### ISSUE TITLE
[Bug] Lspconfig fails to start randomly when this plugin is enabled

### ISSUE THREAD

**Issue by GeorgiChochev** [EvWilson/spelunk.nvim#40]
Hello

I started getting random weird issues occasionally where I dont get syntax highlight when I open some files due to 'nvim-lspconfig' not loading and until I execute ':e' on the buffer the lspconfig fails to load. 

After disabling spelunk the problem magically stop occurring so this is what this issue is about.
There where no errors thrown and sadly I don't really have any useful info to provide.
My best guess its one of the recent commits from the last week since I do update regularly and this started occurring after updating my plugins last night

Let me know if you need anything in particular I can pull out that might help with debugging this one out

**Comment by EvWilson** [comment]
Hey @GeorgiChochev! I was recently able to reproduce your issue after some more changes, and when opening another Python project using `pyright`.
I've pushed a branch with a potential fix in this PR: https://github.com/EvWilson/spelunk.nvim/pull/43
This seems to resolve the problem for me. Could I get your help checking if it resolves it for you as well, before I merge it? If you're using `lazy.nvim` as your package manager, you should be able to try it out by adding this to your plugin spec:
```
branch = 'lsp-startup-issue'
```
Thanks so much for the issue report!

**Comment by EvWilson** [comment]
Going to go ahead and merge this, to live with it myself and see if it solves the issue long-term. Let me know if you keep seeing the issue after updating, but otherwise I'll likely try to close this issue by the end of the weekend.

**Comment by GeorgiChochev** [comment]
Looks to be working, thanks for the patch up
