### ISSUE TITLE
attempt to perform arithmetic on nil value

### ISSUE THREAD

**Issue by jemag** [EvWilson/spelunk.nvim#47]
Currently if mark retrieval fails we will get the following error:
![image](https://github.com/user-attachments/assets/ef298b0b-7169-4ba4-a65c-2877afaa9b6e)

In my case, this happens after restoring a session.

I believe this is because of an error in the `virt_to_physical` function, where if the mark fails to retrieve, you create one, but then the mark is never updated afterwards:
https://github.com/EvWilson/spelunk.nvim/blob/46fc72f148f2337fc554dd9c16c53937b1c35676/lua/spelunk/mark.lua?plain=1#L47-L61
I am guessing once the mark is actually created by `set_mark` then the `mark` local variable should be updated before returning (i.e. performing arithmetic on nil value).

**Comment by EvWilson** [comment]
Hey @jemag! Thanks so much for the issue report. I was able to reproduce this locally and just pushed a small change to address it here: https://github.com/EvWilson/spelunk.nvim/pull/48

This seemed to take care of it for me, could I get your help making sure it works for you as well? Thanks so much for pointing out that error in the recovery logic!

**Comment by jemag** [comment]
works well, thx!
