### ISSUE TITLE
Empty search_current_bookmarks

### ISSUE THREAD

**Issue by jemag** [EvWilson/spelunk.nvim#49]
Currently searching for current stack bookmarks returns an empty list despite there being bookmarks present.
For given bookmarks:
![image](https://github.com/user-attachments/assets/351a0939-1398-4484-bc92-b756ccb65ba3)
Triggering `search_current_bookmarks` results in:
![image](https://github.com/user-attachments/assets/d5729d4b-349f-461b-8d17-e0ac9ce6df75)

I believe this is because the data being sent to telescope is not a proper array with the required values. I.e, these are the values sent for current stack
```lua
DEBUGPRINT[15]: telescope.lua:43: data={
  bookmarks = { {
      bufnr = 1,
      col = 2,
      file = "/home/jemag/Projects/gorestprototype/main.go",
      line = 127,
      mark_id = 1,
      meta = {}
    }, {
      bufnr = 1,
      col = 1,
      file = "/home/jemag/Projects/gorestprototype/main.go",
      line = 76,
      mark_id = 2,
      meta = {}
    }, {
      bufnr = 1,
      col = 1,
      file = "/home/jemag/Projects/gorestprototype/main.go",
      line = 54,
      mark_id = 3,
      meta = {}
    } },
  name = "Default"
}

```

While for the working searching of all marks, these are the values passed
```lua
DEBUGPRINT[15]: telescope.lua:43: data={ {
    bufnr = 1,
    col = 2,
    file = "/home/jemag/Projects/gorestprototype/main.go",
    line = 127,
    mark_id = 1,
    meta = {},
    stack = "Default"
  }, {
    bufnr = 1,
    col = 1,
    file = "/home/jemag/Projects/gorestprototype/main.go",
    line = 76,
    mark_id = 2,
    meta = {},
    stack = "Default"
  }, {
    bufnr = 1,
    col = 1,
    file = "/home/jemag/Projects/gorestprototype/main.go",
    line = 54,
    mark_id = 3,
    meta = {},
    stack = "Default"
  } }

```

**Comment by EvWilson** [comment]
Addressed in https://github.com/EvWilson/spelunk.nvim/pull/51!
Thanks so much for your help, and great issue report!
