### ISSUE TITLE
Quitting UI does not restore cursor to original window

### ISSUE THREAD

**Issue by jemag** [EvWilson/spelunk.nvim#50]
Lauching the UI and then quitting while pressing `q` will not restore the cursor to its original window when having multiple splits (seems to restore to leftmost window at the moment)
![wezterm-gui_RSxgIqC2tS](https://github.com/user-attachments/assets/b11a29e2-5a7b-4f55-8cbf-05202f81aafd)

**Comment by EvWilson** [comment]
Hey there! Thank you for the issue again, took a stab at fixing it up in: https://github.com/EvWilson/spelunk.nvim/pull/52. Let me know if this fixes it all up for you, took it for some cursory testing myself and it seems to be resolved. I'll leave this open until you get a chance to take a look at it!

**Comment by jemag** [comment]
just tested it, unfortunately the behavior seems to be the same (as of 37942e4)

**Comment by EvWilson** [comment]
Hey! Yeah, thanks for catching it. Had it halfway there, mostly for the splits case. Took another stab in https://github.com/EvWilson/spelunk.nvim/pull/53, seems like it should be what we're looking for now.

**Comment by jemag** [comment]
works great now, thanks!
